name: qBittorrent
version: 1.1.2
slug: qbittorrent
description: A BitTorrent client in the classic style with a nice web UI, using qBittorrent from LinuxServer.
startup: services
init: false
arch:
  - amd64
  - aarch64
  - armv7
map:
  - addon_config:rw
  - media:rw
ports:
  "8080/tcp": 8080  # Web UI
  "6881/tcp": 6881  # BitTorrent incoming
  "6881/udp": 6881  # BitTorrent DHT
webui: "http://[HOST]:[PORT:8080]"
environment:
  PUID: "0"
  PGID: "0"
  TZ: "Africa/Johannesburg"