name: "Pi-hole"
description: "Network-wide ad blocking via your own Linux hardware"
version: "1.0.0"
slug: "pihole"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  53/tcp: 53
  53/udp: 53
  80/tcp: 8080
ports_description:
  53/tcp: "DNS TCP"
  53/udp: "DNS UDP"
  80/tcp: "Web interface"
options:
  WEBPASSWORD: "admin"
  TZ: "UTC"
  DNSMASQ_LISTENING: "all"
  PIHOLE_DNS_: "8.8.8.8;8.8.4.4"
  VIRTUAL_HOST: ""
schema:
  WEBPASSWORD: str
  TZ: str
  DNSMASQ_LISTENING: "all|single|local"
  PIHOLE_DNS_: str
  VIRTUAL_HOST: str?
network:
  - "53:53/tcp"
  - "53:53/udp"
host_network: false
privileged:
  - NET_ADMIN
  - NET_RAW
  - NET_BIND_SERVICE
tmpfs: true