name: Ultimate Guitar Scraper
version: 3.6.5
slug: ultimate-guitar-scraper
description: A web scraper for Ultimate Guitar tabs and chords
url: https://github.com/RFC1918-hub/Hassio-Add-ons
webui: "http://[HOST]:[PORT:3000]"
startup: services
arch:
  - amd64
  - aarch64
init: false
map:
  - addon_config:rw
privileged: []
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web interface
options:
  webhook_url: "https://n8n-058ea47.peakhq.co.za/webhook/703db9aa-615a-433c-aff6-67aea85e0712"
  allowed_origins: "http://localhost:3000,http://127.0.0.1:3000,https://chords-45ac23h.peakhq.co.za"
schema:
  webhook_url: str?
  allowed_origins: str?
environment:
  TZ: "Africa/Johannesburg"
