name: Jellyseerr
version: 1.3.0
slug: jellyseerr
description: A free and open-source media request system built for Jellyfin and Plex.
startup: services
init: false
arch:
  - amd64
  - aarch64
  - armv7
map:
  - addon_config:rw
  - media:rw
volumes:
  - share/jellyseerr/config:/app/config
ports:
  "5055/tcp": 5055
webui: "http://[HOST]:[PORT:5055]"
